name: saqinah

on:
  pull_request:
    branches:
      - "master"
  push:
    branches:
      - "master"
      - "development"
jobs:
  saqinah:
    name: saqinah
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter build apk
      - name: Archive Files
        run: |
          sudo apt-get update
          sudo apt-get install zip
          zip -r archive.zip *
      - name: Push to Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*"
          tag: v1.0.${{ github.run_number}}
          token: ${{ secrets.TOKEN}}
      - name: Get Slack web hook
        uses: haya14busa/action-cond@v1
        id: slackwebhook
        with:
          cond: ${{ steps.brach.output.branch == 'master'}}
          if true: ${{ secrets.SLACKWEBHOOK}}
      - name: Notify on slack channel
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: ${{ steps.brach.output.branch }}
          SLACK_COLOR: ${{ job.status}}
          SLACK_MESSAGE: https://github.com/bhadawi404/Saqinah/releases/v1.0.${{ github.run_number}}
          SLACK_USERNAME: Saqinah-bot
          SLACK_WEBHOOK: ${{ steps.slackwebhook.output.value}}



